project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!examples"
    - "!scripts"

website:
  title: "leafcutter2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



